package main

// stubs returns the 319 task definitions that make up the
// "designed but not yet implemented" portion of macbench v0.1.
// Combined with the 50 implemented tasks (001-050), this brings
// macbench to **369 task slots**, matching OSWorld's task count.
//
// Each stub has a real, specific prompt — not "TODO". A future
// implementer can pick any stub and write its setup.sh + eval.sh
// without re-designing the task. Categories + difficulty assignments
// are stable from v0.1 forward.
func stubs() []stub {
	return []stub{
		// ─── Finder (40 stubs, 051-090; 10 already implemented as 001/005-010) ───
		{ID: "051-finder-show-hidden-files", Category: "finder", Difficulty: "T1", Prompt: "Toggle hidden files visibility in Finder (Cmd+Shift+.). The defaults key AppleShowAllFiles flips."},
		{ID: "052-finder-toggle-sidebar", Category: "finder", Difficulty: "T1", Prompt: "Toggle the Finder sidebar visibility (View menu > Hide Sidebar / Show Sidebar)"},
		{ID: "053-finder-toggle-statusbar", Category: "finder", Difficulty: "T1", Prompt: "Toggle the Finder status bar (View menu > Show / Hide Status Bar)"},
		{ID: "054-finder-toggle-pathbar", Category: "finder", Difficulty: "T1", Prompt: "Toggle the Finder path bar (View menu > Show / Hide Path Bar)"},
		{ID: "055-finder-add-to-favorites", Category: "finder", Difficulty: "T1", Prompt: "Add ~/Desktop/kinbench/ to the Finder sidebar Favorites"},
		{ID: "056-finder-quick-look", Category: "finder", Difficulty: "T2", Prompt: "Open Quick Look (spacebar) on a specific file in Finder"},
		{ID: "057-finder-set-view-list", Category: "finder", Difficulty: "T2", Prompt: "Switch the active Finder window to List view (Cmd+2)"},
		{ID: "058-finder-set-view-column", Category: "finder", Difficulty: "T2", Prompt: "Switch the active Finder window to Column view (Cmd+3)"},
		{ID: "059-finder-set-view-gallery", Category: "finder", Difficulty: "T2", Prompt: "Switch the active Finder window to Gallery view (Cmd+4)"},
		{ID: "060-finder-sort-by-date", Category: "finder", Difficulty: "T2", Prompt: "Sort the contents of ~/Desktop/kinbench/ by Date Modified (descending)"},
		{ID: "061-finder-sort-by-size", Category: "finder", Difficulty: "T2", Prompt: "Sort the contents of ~/Documents by File Size (descending)"},
		{ID: "062-finder-search-current-folder", Category: "finder", Difficulty: "T2", Prompt: "In Finder, search the current folder (~/Desktop) for files containing 'kinbench' in their name"},
		{ID: "063-finder-spotlight-search", Category: "finder", Difficulty: "T2", Prompt: "Use Spotlight (Cmd+Space) to find a file named 'kinbench-target.txt' and reveal it in Finder"},
		{ID: "064-finder-tag-multiple-colors", Category: "finder", Difficulty: "T2", Prompt: "Apply both the Yellow and Green color tags to the file ~/Desktop/kinbench/064-multi-tag.txt"},
		{ID: "065-finder-remove-all-tags", Category: "finder", Difficulty: "T2", Prompt: "Remove all color tags from the file ~/Desktop/kinbench/065-tagged.txt"},
		{ID: "066-finder-color-label-blue", Category: "finder", Difficulty: "T2", Prompt: "Apply the Blue color tag (specifically Blue, not Red) to ~/Desktop/kinbench/066-target.txt"},
		{ID: "067-finder-create-zip-from-multiple", Category: "finder", Difficulty: "T2", Prompt: "Compress the 5 files in ~/Desktop/kinbench/067-files/ into a single archive at ~/Desktop/kinbench/067-archive.zip"},
		{ID: "068-finder-extract-zip", Category: "finder", Difficulty: "T2", Prompt: "Extract the archive ~/Desktop/kinbench/068-bundle.zip into ~/Desktop/kinbench/068-extracted/"},
		{ID: "069-finder-set-folder-icon", Category: "finder", Difficulty: "T2", Prompt: "Change the icon of the folder ~/Desktop/kinbench/069-folder/ to a custom image (paste from clipboard via Get Info)"},
		{ID: "070-finder-show-package-contents", Category: "finder", Difficulty: "T2", Prompt: "Right-click TextEdit.app and choose Show Package Contents to inspect its bundle structure"},
		{ID: "071-finder-go-to-folder", Category: "finder", Difficulty: "T2", Prompt: "Use Cmd+Shift+G ('Go to Folder') in Finder to navigate to /tmp"},
		{ID: "072-finder-recent-items", Category: "finder", Difficulty: "T2", Prompt: "Open a file from the Apple menu's Recent Items list"},
		{ID: "073-finder-create-smart-folder", Category: "finder", Difficulty: "T2", Prompt: "Create a Smart Folder titled 'KinBench Today' that shows files modified today, save to sidebar"},
		{ID: "074-finder-pin-folder-sidebar", Category: "finder", Difficulty: "T2", Prompt: "Pin the folder ~/Documents/kinbench-pinned/ to the Finder sidebar"},
		{ID: "075-finder-rename-extension", Category: "finder", Difficulty: "T2", Prompt: "Rename ~/Desktop/kinbench/075-doc.txt to 075-doc.md (changing the extension; keep contents)"},
		{ID: "076-finder-batch-rename-replace", Category: "finder", Difficulty: "T2", Prompt: "In ~/Desktop/kinbench/076-files/, batch-rename: replace 'draft' with 'final' in 3 file names (Finder's Rename feature)"},
		{ID: "077-finder-create-symlink", Category: "finder", Difficulty: "T2", Prompt: "Create a symbolic link at ~/Desktop/kinbench/077-link pointing to ~/Desktop/kinbench/077-target.txt"},
		{ID: "078-finder-burn-folder", Category: "finder", Difficulty: "T2", Prompt: "Create a Burn Folder named 'KinBench Burn' on the Desktop"},
		{ID: "079-finder-empty-trash", Category: "finder", Difficulty: "T2", Prompt: "Empty the Trash (Finder menu > Empty Trash, confirm)"},
		{ID: "080-finder-show-on-desktop", Category: "finder", Difficulty: "T2", Prompt: "In Finder Preferences, enable 'Show these items on the desktop: Hard disks'"},
		{ID: "081-finder-find-largest-file", Category: "finder", Difficulty: "T3", Prompt: "Find the largest file in ~/Documents/ (recursive search) and write its full path + size in bytes to ~/Desktop/kinbench/081-largest.txt", TimeoutSec: 240},
		{ID: "082-finder-find-duplicates", Category: "finder", Difficulty: "T3", Prompt: "Identify any duplicate files in ~/Desktop/kinbench/082-files/ (same size + same content) and write a list of duplicate pairs to ~/Desktop/kinbench/082-dupes.txt", TimeoutSec: 240},
		{ID: "083-finder-organize-by-type", Category: "finder", Difficulty: "T3", Prompt: "Organize the loose files in ~/Desktop/kinbench/083-mixed/ into subfolders by type: Images/ (jpg, png, heic), Documents/ (pdf, txt, md), Other/ (everything else)", TimeoutSec: 240},
		{ID: "084-finder-archive-old-files", Category: "finder", Difficulty: "T3", Prompt: "Move all files in ~/Desktop/kinbench/084-source/ that are older than 30 days to ~/Desktop/kinbench/084-archive/", TimeoutSec: 180},
		{ID: "085-finder-rename-from-clipboard-list", Category: "finder", Difficulty: "T3", Prompt: "The clipboard contains 3 lines, one new name per line. Rename the 3 files in ~/Desktop/kinbench/085-rename/ in alphabetical order, applying the clipboard names in order"},
		{ID: "086-finder-recursive-rename-extension", Category: "finder", Difficulty: "T3", Prompt: "Recursively rename all .heic files in ~/Desktop/kinbench/086-photos/ (and subfolders) to .jpg (keeping content + filename stem)", TimeoutSec: 180},
		{ID: "087-finder-folder-size-report", Category: "finder", Difficulty: "T3", Prompt: "Compute the total size of each top-level folder in ~/Desktop/kinbench/087-tree/ and write a report (one line per folder, format 'NAME SIZE_BYTES') to ~/Desktop/kinbench/087-sizes.txt"},
		{ID: "088-finder-find-by-content", Category: "finder", Difficulty: "T3", Prompt: "Find all .txt files in ~/Desktop/kinbench/088-corpus/ that contain the word 'kinbench' and write their full paths (one per line) to ~/Desktop/kinbench/088-matches.txt"},
		{ID: "089-finder-zip-with-password", Category: "finder", Difficulty: "T3", Prompt: "Create a password-protected zip archive of ~/Desktop/kinbench/089-secret/ at ~/Desktop/kinbench/089-secret.zip (password: 'kinbench')"},
		{ID: "090-finder-flatten-folder", Category: "finder", Difficulty: "T3", Prompt: "Flatten the nested folder structure in ~/Desktop/kinbench/090-tree/: move all files (recursive) into ~/Desktop/kinbench/090-flat/ (preserving filenames; on conflict suffix _1, _2)", TimeoutSec: 180},

		// ─── Safari (34 stubs, 091-124; 6 already implemented as 002, 011-013, 034-035) ───
		{ID: "091-safari-bookmark-page", Category: "safari", Difficulty: "T1", Prompt: "Bookmark the current Safari front page (Cmd+D, accept default name + folder)"},
		{ID: "092-safari-show-history", Category: "safari", Difficulty: "T1", Prompt: "Open Safari's full History view (Cmd+Y or History menu > Show All History)"},
		{ID: "093-safari-show-bookmarks", Category: "safari", Difficulty: "T1", Prompt: "Open Safari's bookmarks view (Cmd+Option+B)"},
		{ID: "094-safari-show-reading-list", Category: "safari", Difficulty: "T1", Prompt: "Open Safari's Reading List sidebar"},
		{ID: "095-safari-zoom-in", Category: "safari", Difficulty: "T1", Prompt: "Zoom in on the current Safari page 3 times (Cmd+= three times)"},
		{ID: "096-safari-zoom-reset", Category: "safari", Difficulty: "T1", Prompt: "Reset Safari's zoom on the current page to 100% (Cmd+0)"},
		{ID: "097-safari-show-developer-menu", Category: "safari", Difficulty: "T1", Prompt: "Enable the Develop menu in Safari (Settings > Advanced > 'Show features for web developers')"},
		{ID: "098-safari-private-window-go", Category: "safari", Difficulty: "T1", Prompt: "Open a new Safari Private Window (Shift+Cmd+N) and navigate to https://en.wikipedia.org"},
		{ID: "099-safari-fill-search-form", Category: "safari", Difficulty: "T2", Prompt: "Open google.com in Safari, type 'macOS computer use' into the search box, press Return"},
		{ID: "100-safari-add-reading-list", Category: "safari", Difficulty: "T2", Prompt: "Add the current Safari page (https://en.wikipedia.org/wiki/macOS) to Reading List"},
		{ID: "101-safari-bookmark-in-folder", Category: "safari", Difficulty: "T2", Prompt: "Bookmark the current page into a specific bookmarks folder named 'KinBench' (create the folder if it doesn't exist)"},
		{ID: "102-safari-find-in-page", Category: "safari", Difficulty: "T2", Prompt: "Use Cmd+F on the current Safari page to find the term 'macOS' and highlight matches"},
		{ID: "103-safari-print-as-pdf", Category: "safari", Difficulty: "T2", Prompt: "Save the current Safari page as a PDF to ~/Desktop/kinbench/103-page.pdf (File > Export as PDF)", TimeoutSec: 180},
		{ID: "104-safari-share-via-mail", Category: "safari", Difficulty: "T2", Prompt: "Share the current Safari page via Mail (Share button > Mail) — leave the draft as a draft"},
		{ID: "105-safari-take-snapshot", Category: "safari", Difficulty: "T2", Prompt: "Use Safari's File > Save As Web Archive feature to save the current page to ~/Desktop/kinbench/105-page.webarchive"},
		{ID: "106-safari-clear-history", Category: "safari", Difficulty: "T2", Prompt: "Clear Safari's browsing history for 'the last hour' (History > Clear History > 'the last hour')"},
		{ID: "107-safari-clear-cookies", Category: "safari", Difficulty: "T2", Prompt: "In Safari Settings > Privacy > Manage Website Data, delete the data for example.com specifically"},
		{ID: "108-safari-set-default-search-engine", Category: "safari", Difficulty: "T2", Prompt: "Change Safari's default search engine to DuckDuckGo (Settings > Search > Search engine)"},
		{ID: "109-safari-disable-popup-blocker", Category: "safari", Difficulty: "T2", Prompt: "In Safari Settings > Websites > Pop-up Windows, allow popups for example.com"},
		{ID: "110-safari-enable-extension", Category: "safari", Difficulty: "T2", Prompt: "Enable the first installed Safari extension in Settings > Extensions (or report 'no extensions installed' if list is empty)"},
		{ID: "111-safari-pin-multiple-tabs", Category: "safari", Difficulty: "T2", Prompt: "In a single Safari window, pin three tabs: apple.com, github.com, en.wikipedia.org"},
		{ID: "112-safari-mute-tab", Category: "safari", Difficulty: "T2", Prompt: "Mute a Safari tab playing audio (right-click tab > Mute Tab, or click the speaker icon in the tab)"},
		{ID: "113-safari-rearrange-tabs", Category: "safari", Difficulty: "T2", Prompt: "Rearrange Safari tabs so that apple.com is the first tab in the front window (drag-and-drop the tab)"},
		{ID: "114-safari-tab-group-create", Category: "safari", Difficulty: "T2", Prompt: "Create a new Tab Group in Safari named 'KinBench Research' (sidebar > '+' next to Tab Groups)"},
		{ID: "115-safari-tab-group-move-tab", Category: "safari", Difficulty: "T2", Prompt: "Move the current front tab into the 'KinBench Research' Tab Group (right-click tab > Move to Tab Group)"},
		{ID: "116-safari-show-source", Category: "safari", Difficulty: "T2", Prompt: "View the page source of the current Safari page (Develop menu > Show Page Source). Develop menu must be enabled first."},
		{ID: "117-safari-inspect-element", Category: "safari", Difficulty: "T2", Prompt: "Open Safari's Web Inspector for the current page (Develop menu > Show Web Inspector). Develop menu must be enabled first."},
		{ID: "118-safari-translate-page", Category: "safari", Difficulty: "T2", Prompt: "Translate the current Safari page to English (Translate menu in the URL bar, if available; report 'translation not available' if the source is already English)"},
		{ID: "119-safari-multi-page-research", Category: "safari", Difficulty: "T3", Prompt: "Open three Safari tabs (apple.com/macos, en.wikipedia.org/wiki/macOS, github.com), find the year macOS was first released, and write that 4-digit year to ~/Desktop/kinbench/119-year.txt", TimeoutSec: 240},
		{ID: "120-safari-form-fill-multi-step", Category: "safari", Difficulty: "T3", Prompt: "Navigate to https://duckduckgo.com, perform a search for 'kinbench', then click on the first non-ad result"},
		{ID: "121-safari-download-file", Category: "safari", Difficulty: "T3", Prompt: "Navigate to https://www.gnu.org/licenses/gpl-3.0.txt and download the file (file should land in ~/Downloads/)"},
		{ID: "122-safari-history-search-then-open", Category: "safari", Difficulty: "T3", Prompt: "Search Safari's browsing history for 'apple', then click the first matching entry to open it"},
		{ID: "123-safari-bookmark-export", Category: "safari", Difficulty: "T3", Prompt: "Export Safari bookmarks as HTML (File > Export > Bookmarks) to ~/Desktop/kinbench/123-bookmarks.html"},
		{ID: "124-safari-tab-management-cleanup", Category: "safari", Difficulty: "T3", Prompt: "The Safari window has 5 tabs open. Close every tab except the ones showing apple.com and github.com (leaving exactly 2 tabs open)"},

		// ─── Mail (39 stubs, 125-163; 1 already implemented as 016) ───
		{ID: "125-mail-mark-as-read", Category: "mail", Difficulty: "T1", Prompt: "Mark the most recent unread message in the Inbox as read"},
		{ID: "126-mail-mark-as-unread", Category: "mail", Difficulty: "T1", Prompt: "Mark a specific already-read message as unread"},
		{ID: "127-mail-flag-red", Category: "mail", Difficulty: "T1", Prompt: "Apply the red flag to the most recent message in the Inbox"},
		{ID: "128-mail-flag-blue", Category: "mail", Difficulty: "T1", Prompt: "Apply the blue flag (specifically blue, not red) to a specific message"},
		{ID: "129-mail-archive-message", Category: "mail", Difficulty: "T1", Prompt: "Archive the most recent Inbox message (move to Archive mailbox)"},
		{ID: "130-mail-move-to-junk", Category: "mail", Difficulty: "T1", Prompt: "Mark a specific message as Junk (Message > Move to Junk)"},
		{ID: "131-mail-print-as-pdf", Category: "mail", Difficulty: "T1", Prompt: "Save the most recent Inbox message as PDF to ~/Desktop/kinbench/131-message.pdf"},
		{ID: "132-mail-vip-add", Category: "mail", Difficulty: "T1", Prompt: "Add the sender of the most recent Inbox message to the VIP list"},
		{ID: "133-mail-vip-remove", Category: "mail", Difficulty: "T1", Prompt: "Remove a specific sender from the VIP list"},
		{ID: "134-mail-empty-trash", Category: "mail", Difficulty: "T1", Prompt: "Empty Mail's Trash mailbox (Mailbox menu > Erase Deleted Items > In All Accounts)"},
		{ID: "135-mail-reply-to-message", Category: "mail", Difficulty: "T2", Prompt: "Reply to the most recent Inbox message with body 'KinBench 135 reply'. Don't send — leave the reply as a draft."},
		{ID: "136-mail-reply-all", Category: "mail", Difficulty: "T2", Prompt: "Reply-all to a multi-recipient message in the Inbox with body 'KinBench 136 reply-all'. Save as draft."},
		{ID: "137-mail-forward-message", Category: "mail", Difficulty: "T2", Prompt: "Forward a specific Inbox message to test@example.com. Save as draft."},
		{ID: "138-mail-add-cc", Category: "mail", Difficulty: "T2", Prompt: "Compose a draft email to test@example.com, with cc: cc@example.com. Subject: 'KinBench 138'. Save as draft."},
		{ID: "139-mail-add-bcc", Category: "mail", Difficulty: "T2", Prompt: "Compose a draft email with bcc: bcc@example.com. Subject: 'KinBench 139'. Save as draft."},
		{ID: "140-mail-attach-file-to-draft", Category: "mail", Difficulty: "T2", Prompt: "Compose a draft, subject 'KinBench 140'. Attach the file ~/Desktop/kinbench/140-attach.txt. Save as draft."},
		{ID: "141-mail-add-signature", Category: "mail", Difficulty: "T2", Prompt: "Compose a draft and apply a specific Mail signature (use any signature configured in your Mail settings). Subject: 'KinBench 141'."},
		{ID: "142-mail-search-by-sender", Category: "mail", Difficulty: "T2", Prompt: "Use Mail's search to find all messages from a specific sender. Write the count to ~/Desktop/kinbench/142-count.txt"},
		{ID: "143-mail-search-by-subject", Category: "mail", Difficulty: "T2", Prompt: "Search Mail for messages with subject containing 'receipt'. Write the count to ~/Desktop/kinbench/143-count.txt"},
		{ID: "144-mail-search-by-date-range", Category: "mail", Difficulty: "T2", Prompt: "Search Mail for messages received this week. Write the count to ~/Desktop/kinbench/144-count.txt"},
		{ID: "145-mail-search-with-attachment", Category: "mail", Difficulty: "T2", Prompt: "Search Mail for messages that have attachments. Write the count to ~/Desktop/kinbench/145-count.txt"},
		{ID: "146-mail-move-to-mailbox", Category: "mail", Difficulty: "T2", Prompt: "Move a specific Inbox message to a sub-mailbox named 'KinBench 146' (create if needed)"},
		{ID: "147-mail-create-mailbox", Category: "mail", Difficulty: "T2", Prompt: "Create a new mailbox folder named 'kinbench-test-mailbox'"},
		{ID: "148-mail-rename-mailbox", Category: "mail", Difficulty: "T2", Prompt: "Rename a custom mailbox from its current name to 'kinbench-renamed'"},
		{ID: "149-mail-delete-mailbox", Category: "mail", Difficulty: "T2", Prompt: "Delete the custom mailbox named 'kinbench-deleteme'"},
		{ID: "150-mail-create-rule", Category: "mail", Difficulty: "T2", Prompt: "Create a Mail rule that flags messages whose subject contains 'kinbench-rule'"},
		{ID: "151-mail-create-smart-mailbox", Category: "mail", Difficulty: "T2", Prompt: "Create a Smart Mailbox titled 'KinBench This Month' showing messages received this month"},
		{ID: "152-mail-block-sender", Category: "mail", Difficulty: "T2", Prompt: "Add a specific sender to Mail's blocked senders list (Settings > Junk Mail > Blocked)"},
		{ID: "153-mail-mute-conversation", Category: "mail", Difficulty: "T2", Prompt: "Mute a specific conversation/thread (Message > Mute)"},
		{ID: "154-mail-mark-junk-then-not", Category: "mail", Difficulty: "T2", Prompt: "Mark a message as junk, then mark the same message as 'not junk' (reverse the action)"},
		{ID: "155-mail-find-attachment-then-save", Category: "mail", Difficulty: "T3", Prompt: "Find a message with a PDF attachment in the Inbox. Save the attachment to ~/Desktop/kinbench/155-attachment.pdf", TimeoutSec: 240},
		{ID: "156-mail-reply-with-attached-screenshot", Category: "mail", Difficulty: "T3", Prompt: "Reply to a specific message with a fresh screenshot attached. Body: 'KinBench 156'. Save as draft.", TimeoutSec: 240},
		{ID: "157-mail-forward-then-archive", Category: "mail", Difficulty: "T3", Prompt: "Forward a specific message to test@example.com (save as draft), then archive the original"},
		{ID: "158-mail-bulk-archive-by-sender", Category: "mail", Difficulty: "T3", Prompt: "Archive every Inbox message from a specific sender (5+ messages)", TimeoutSec: 240},
		{ID: "159-mail-summarize-then-reply", Category: "mail", Difficulty: "T3", Prompt: "Read a specific multi-message thread, summarize the key points (2-3 sentences) in a reply to the most recent message. Save as draft."},
		{ID: "160-mail-search-then-flag", Category: "mail", Difficulty: "T3", Prompt: "Search Mail for messages with subject containing 'kinbench-160', flag every match with the red flag", TimeoutSec: 180},
		{ID: "161-mail-export-conversation", Category: "mail", Difficulty: "T3", Prompt: "Export a specific conversation thread as a single PDF to ~/Desktop/kinbench/161-thread.pdf", TimeoutSec: 240},
		{ID: "162-mail-resend-bounce", Category: "mail", Difficulty: "T3", Prompt: "Find a draft message in the Drafts mailbox titled 'KinBench 162 Resend' and modify it to add 'Re-sending' to the subject. Save as draft."},
		{ID: "163-mail-cleanup-promotions", Category: "mail", Difficulty: "T3", Prompt: "Move all messages in the Inbox whose subject contains 'promo' or 'sale' to a folder called 'kinbench-promos'", TimeoutSec: 240},

		// ─── Notes (25 stubs, 164-188; 5 already implemented as 003, 014, 015, 036, 037) ───
		{ID: "164-notes-pin-note", Category: "notes", Difficulty: "T1", Prompt: "Pin the note titled 'KinBench Pinned 164' to the top of the notes list"},
		{ID: "165-notes-unpin-note", Category: "notes", Difficulty: "T1", Prompt: "Unpin a previously-pinned note titled 'KinBench Unpin 165'"},
		{ID: "166-notes-lock-note", Category: "notes", Difficulty: "T1", Prompt: "Lock the note titled 'KinBench Lock 166' with a password"},
		{ID: "167-notes-share-note-via-mail", Category: "notes", Difficulty: "T1", Prompt: "Share the note 'KinBench Share 167' via Mail (Share button). Save the resulting email as a draft."},
		{ID: "168-notes-print-note", Category: "notes", Difficulty: "T1", Prompt: "Save the note 'KinBench Print 168' as PDF to ~/Desktop/kinbench/168-note.pdf"},
		{ID: "169-notes-add-checklist", Category: "notes", Difficulty: "T2", Prompt: "Add a 3-item checklist to the existing note 'KinBench Checklist 169' (Format > Checklist or Cmd+Shift+L)"},
		{ID: "170-notes-mark-checklist-item", Category: "notes", Difficulty: "T2", Prompt: "Mark the second item in the checklist of note 'KinBench Mark 170' as done"},
		{ID: "171-notes-add-image", Category: "notes", Difficulty: "T2", Prompt: "Insert the image ~/Desktop/kinbench/171-photo.jpg into the note 'KinBench Image 171'"},
		{ID: "172-notes-add-table", Category: "notes", Difficulty: "T2", Prompt: "Add a 3x3 table to the note 'KinBench Table 172' (Format > Table or Cmd+Option+T)"},
		{ID: "173-notes-format-bold", Category: "notes", Difficulty: "T2", Prompt: "In the note 'KinBench Bold 173', make the phrase 'this is bold' actually bold"},
		{ID: "174-notes-format-headline", Category: "notes", Difficulty: "T2", Prompt: "In the note 'KinBench Heading 174', apply Heading style to the first line"},
		{ID: "175-notes-create-folder", Category: "notes", Difficulty: "T2", Prompt: "Create a new folder named 'kinbench-folder' in the Notes app sidebar"},
		{ID: "176-notes-move-note-to-folder", Category: "notes", Difficulty: "T2", Prompt: "Move the note 'KinBench Move 176' into the folder 'kinbench-folder'"},
		{ID: "177-notes-create-link-between-notes", Category: "notes", Difficulty: "T2", Prompt: "In the note 'KinBench Source 177', add a wiki-style link to the note 'KinBench Target 177' (use >> or @)"},
		{ID: "178-notes-find-and-replace", Category: "notes", Difficulty: "T2", Prompt: "In the note 'KinBench Replace 178', find 'version 1' and replace with 'version 2'"},
		{ID: "179-notes-search-all-notes", Category: "notes", Difficulty: "T2", Prompt: "Search all Notes for the term 'kinbench-search-179' and write the count of matching notes to ~/Desktop/kinbench/179-count.txt"},
		{ID: "180-notes-tag-note", Category: "notes", Difficulty: "T2", Prompt: "Add a #kinbench tag to the note 'KinBench Tag 180' (type # then 'kinbench')"},
		{ID: "181-notes-filter-by-tag", Category: "notes", Difficulty: "T2", Prompt: "Filter the Notes view to show only notes tagged with #kinbench"},
		{ID: "182-notes-export-note", Category: "notes", Difficulty: "T2", Prompt: "Export the note 'KinBench Export 182' as PDF to ~/Desktop/kinbench/182-note.pdf"},
		{ID: "183-notes-undo-multiple-edits", Category: "notes", Difficulty: "T2", Prompt: "In the note 'KinBench Undo 183', press Cmd+Z 5 times to undo the last 5 edits"},
		{ID: "184-notes-aggregate-checklists", Category: "notes", Difficulty: "T3", Prompt: "Find all notes whose names start with 'KinBench Checklist Source' and aggregate their unchecked checklist items into a master note 'KinBench Aggregate 184'", TimeoutSec: 240},
		{ID: "185-notes-merge-two-notes", Category: "notes", Difficulty: "T3", Prompt: "Merge the contents of 'KinBench Merge A 185' and 'KinBench Merge B 185' into a single new note 'KinBench Merged 185'"},
		{ID: "186-notes-search-then-export", Category: "notes", Difficulty: "T3", Prompt: "Search Notes for 'kinbench-186' and export each matching note as a separate PDF to ~/Desktop/kinbench/186-exports/", TimeoutSec: 300},
		{ID: "187-notes-from-clipboard", Category: "notes", Difficulty: "T3", Prompt: "Create a new note titled 'KinBench Clipboard 187' containing the text currently in the system clipboard"},
		{ID: "188-notes-bulk-delete-tagged", Category: "notes", Difficulty: "T3", Prompt: "Delete every note in Notes that has the #kinbench-archive tag", TimeoutSec: 240},

		// ─── Calendar (29 stubs, 189-217; 6 already implemented as 017-020, 038, 039) ───
		{ID: "189-calendar-go-to-today", Category: "calendar", Difficulty: "T1", Prompt: "In Calendar, navigate to today's date (Cmd+T or 'Today' button in toolbar)"},
		{ID: "190-calendar-switch-to-month", Category: "calendar", Difficulty: "T1", Prompt: "Switch Calendar view to Month (Cmd+3 or View > by Month)"},
		{ID: "191-calendar-switch-to-week", Category: "calendar", Difficulty: "T1", Prompt: "Switch Calendar view to Week (Cmd+2 or View > by Week)"},
		{ID: "192-calendar-switch-to-day", Category: "calendar", Difficulty: "T1", Prompt: "Switch Calendar view to Day (Cmd+1 or View > by Day)"},
		{ID: "193-calendar-search-event", Category: "calendar", Difficulty: "T1", Prompt: "Use Calendar's search to find an event titled 'KinBench Search 193' and select it"},
		{ID: "194-calendar-toggle-mini-calendar", Category: "calendar", Difficulty: "T1", Prompt: "Toggle the mini calendar in the Calendar sidebar (View > Hide Calendar List / Show Calendar List)"},
		{ID: "195-calendar-print-month", Category: "calendar", Difficulty: "T1", Prompt: "Print the current Calendar month view as PDF to ~/Desktop/kinbench/195-month.pdf"},
		{ID: "196-calendar-go-to-date", Category: "calendar", Difficulty: "T1", Prompt: "Use View > Go to Date (Cmd+Shift+T) to navigate to March 15, 2027"},
		{ID: "197-calendar-create-recurring", Category: "calendar", Difficulty: "T2", Prompt: "Create a recurring weekly event 'KinBench Weekly 197' starting tomorrow at 10 AM, repeating every Monday"},
		{ID: "198-calendar-create-event-with-alert", Category: "calendar", Difficulty: "T2", Prompt: "Create an event 'KinBench Alert 198' tomorrow at 3 PM with a 15-minute reminder alert"},
		{ID: "199-calendar-create-event-with-attendees", Category: "calendar", Difficulty: "T2", Prompt: "Create an event 'KinBench Invite 199' tomorrow at 4 PM and invite test1@example.com and test2@example.com (do not actually send invites — just add as attendees)"},
		{ID: "200-calendar-create-all-day", Category: "calendar", Difficulty: "T2", Prompt: "Create an all-day event titled 'KinBench All-Day 200' for tomorrow"},
		{ID: "201-calendar-attach-url", Category: "calendar", Difficulty: "T2", Prompt: "Add a URL (https://localkin.ai) to an existing calendar event titled 'KinBench URL 201'"},
		{ID: "202-calendar-attach-file", Category: "calendar", Difficulty: "T2", Prompt: "Attach the file ~/Desktop/kinbench/202-attach.txt to the existing calendar event 'KinBench Attach 202'"},
		{ID: "203-calendar-change-calendar", Category: "calendar", Difficulty: "T2", Prompt: "Move the event 'KinBench Move 203' from its current calendar to a different calendar"},
		{ID: "204-calendar-set-event-color", Category: "calendar", Difficulty: "T2", Prompt: "Change the calendar of event 'KinBench Color 204' so it displays in a different color"},
		{ID: "205-calendar-add-note-to-event", Category: "calendar", Difficulty: "T2", Prompt: "Add a notes/description text 'KinBench note for event 205' to the existing event 'KinBench Note 205'"},
		{ID: "206-calendar-respond-invitation", Category: "calendar", Difficulty: "T2", Prompt: "Respond 'Accept' to a pending calendar invitation"},
		{ID: "207-calendar-decline-invitation", Category: "calendar", Difficulty: "T2", Prompt: "Respond 'Decline' to a pending calendar invitation"},
		{ID: "208-calendar-create-from-natural-language", Category: "calendar", Difficulty: "T2", Prompt: "Use Calendar's Quick Event entry (File > New Event with Natural Language, or '+' button) to create: 'Lunch with Bob tomorrow at noon'"},
		{ID: "209-calendar-show-availability", Category: "calendar", Difficulty: "T2", Prompt: "Find available 1-hour time slots tomorrow between 9 AM and 5 PM, and write them (one per line, format 'HH:MM-HH:MM') to ~/Desktop/kinbench/209-slots.txt"},
		{ID: "210-calendar-show-week-numbers", Category: "calendar", Difficulty: "T2", Prompt: "Toggle the display of week numbers in Calendar (Settings > General)"},
		{ID: "211-calendar-add-birthday-calendar", Category: "calendar", Difficulty: "T2", Prompt: "Show or hide the Birthdays calendar (Calendar list checkbox)"},
		{ID: "212-calendar-merge-duplicate-events", Category: "calendar", Difficulty: "T3", Prompt: "Find duplicate events titled 'KinBench Dup 212' (same title, same time) and delete the duplicates, keeping one", TimeoutSec: 240},
		{ID: "213-calendar-bulk-move-events", Category: "calendar", Difficulty: "T3", Prompt: "Move every event titled 'KinBench Bulk' from its current calendar to a calendar named 'KinBench Calendar' (create the calendar if it doesn't exist)", TimeoutSec: 240},
		{ID: "214-calendar-export-week", Category: "calendar", Difficulty: "T3", Prompt: "Export this week's events to an .ics file at ~/Desktop/kinbench/214-week.ics"},
		{ID: "215-calendar-import-ics", Category: "calendar", Difficulty: "T3", Prompt: "Import events from the file ~/Desktop/kinbench/215-import.ics into Calendar (double-click the file or File > Import)"},
		{ID: "216-calendar-find-conflict", Category: "calendar", Difficulty: "T3", Prompt: "Identify scheduling conflicts (overlapping events) in the next 7 days and write a list to ~/Desktop/kinbench/216-conflicts.txt (one conflict per line, format 'HH:MM Event A vs Event B')", TimeoutSec: 240},
		{ID: "217-calendar-event-from-mail", Category: "calendar", Difficulty: "T3", Prompt: "Find a Mail message containing flight info (subject contains 'flight'), create a calendar event from the departure date/time", TimeoutSec: 300},

		// ─── Reminders (22 stubs, 218-239; 3 already implemented as 045-047) ───
		{ID: "218-reminders-create-with-list", Category: "reminders", Difficulty: "T1", Prompt: "Create a reminder titled 'KinBench List Item 218' in a specific list named 'kinbench-list-218'. Create the list first if it doesn't exist."},
		{ID: "219-reminders-add-priority", Category: "reminders", Difficulty: "T1", Prompt: "Set the priority of the reminder 'KinBench Priority 219' to High"},
		{ID: "220-reminders-add-flag", Category: "reminders", Difficulty: "T1", Prompt: "Flag the reminder 'KinBench Flag 220'"},
		{ID: "221-reminders-show-flagged", Category: "reminders", Difficulty: "T1", Prompt: "Switch to the Flagged smart list in Reminders (sidebar > Flagged)"},
		{ID: "222-reminders-show-today", Category: "reminders", Difficulty: "T1", Prompt: "Switch to the Today smart list in Reminders (sidebar > Today)"},
		{ID: "223-reminders-create-list", Category: "reminders", Difficulty: "T2", Prompt: "Create a new reminder list named 'kinbench-list-223'"},
		{ID: "224-reminders-rename-list", Category: "reminders", Difficulty: "T2", Prompt: "Rename the reminder list 'kinbench-rename-pre' to 'kinbench-rename-post'"},
		{ID: "225-reminders-delete-list", Category: "reminders", Difficulty: "T2", Prompt: "Delete the reminder list named 'kinbench-deleteme-225'"},
		{ID: "226-reminders-create-with-location", Category: "reminders", Difficulty: "T2", Prompt: "Create a reminder titled 'KinBench Location 226' with a location-based trigger ('Apple Park, Cupertino' or any address — the geofence binding is what matters, not actual triggering)"},
		{ID: "227-reminders-add-subtask", Category: "reminders", Difficulty: "T2", Prompt: "Add a subtask titled 'KinBench Subtask A 227' to the existing reminder 'KinBench Parent 227'"},
		{ID: "228-reminders-mark-subtask", Category: "reminders", Difficulty: "T2", Prompt: "Mark the subtask 'KinBench Subtask 228' (under 'KinBench Parent 228') as completed"},
		{ID: "229-reminders-add-note", Category: "reminders", Difficulty: "T2", Prompt: "Add a note/description 'KinBench Notes 229' to the reminder 'KinBench Description 229'"},
		{ID: "230-reminders-attach-image", Category: "reminders", Difficulty: "T2", Prompt: "Attach the image ~/Desktop/kinbench/230-img.jpg to the reminder 'KinBench Image 230'"},
		{ID: "231-reminders-set-recurring", Category: "reminders", Difficulty: "T2", Prompt: "Set the reminder 'KinBench Recurring 231' to repeat weekly"},
		{ID: "232-reminders-add-tag", Category: "reminders", Difficulty: "T2", Prompt: "Add a #kinbench tag to the reminder 'KinBench Tag 232'"},
		{ID: "233-reminders-filter-by-tag", Category: "reminders", Difficulty: "T2", Prompt: "Filter Reminders to show only items tagged with #kinbench"},
		{ID: "234-reminders-share-list", Category: "reminders", Difficulty: "T2", Prompt: "Open the share sheet for the reminder list 'kinbench-share-234' (don't actually share — just open the share UI)"},
		{ID: "235-reminders-from-mail", Category: "reminders", Difficulty: "T3", Prompt: "Find a Mail message in the Inbox containing action items (e.g. 'Please do X, Y, Z'), create a reminder for each action item", TimeoutSec: 300},
		{ID: "236-reminders-cleanup-completed", Category: "reminders", Difficulty: "T3", Prompt: "Delete every completed reminder in the Reminders app (across all lists)", TimeoutSec: 240},
		{ID: "237-reminders-bulk-priority", Category: "reminders", Difficulty: "T3", Prompt: "Set the priority to High on every reminder due today", TimeoutSec: 240},
		{ID: "238-reminders-export-list", Category: "reminders", Difficulty: "T3", Prompt: "Export every reminder in the list 'kinbench-export-238' to a text file at ~/Desktop/kinbench/238-list.txt (one reminder per line: name + due date if set)"},
		{ID: "239-reminders-import-from-file", Category: "reminders", Difficulty: "T3", Prompt: "Read the markdown checklist at ~/Desktop/kinbench/239-checklist.md ('- [ ] item' format), create a reminder in the list 'kinbench-imported' for each unchecked item"},

		// ─── Settings (43 stubs, 240-282; 7 already implemented as 004, 021-023, 040-042) ───
		{ID: "240-settings-toggle-bluetooth", Category: "settings", Difficulty: "T1", Prompt: "Toggle Bluetooth (turn it off if on, or on if off; either via Control Center or System Settings)"},
		{ID: "241-settings-toggle-wifi", Category: "settings", Difficulty: "T1", Prompt: "Toggle Wi-Fi off then back on (Control Center or System Settings > Wi-Fi)"},
		{ID: "242-settings-toggle-airdrop", Category: "settings", Difficulty: "T1", Prompt: "Toggle AirDrop visibility between 'Contacts Only' and 'Everyone for 10 minutes'"},
		{ID: "243-settings-toggle-handoff", Category: "settings", Difficulty: "T1", Prompt: "Toggle Handoff (System Settings > General > AirDrop & Handoff > Allow Handoff between this Mac and your iCloud devices)"},
		{ID: "244-settings-toggle-stage-manager", Category: "settings", Difficulty: "T1", Prompt: "Toggle Stage Manager via Control Center"},
		{ID: "245-settings-toggle-night-shift", Category: "settings", Difficulty: "T1", Prompt: "Enable Night Shift right now (System Settings > Displays > Night Shift > Manual: Turn On Until Tomorrow)"},
		{ID: "246-settings-toggle-true-tone", Category: "settings", Difficulty: "T1", Prompt: "Toggle True Tone display setting (System Settings > Displays > True Tone)"},
		{ID: "247-settings-toggle-low-power", Category: "settings", Difficulty: "T1", Prompt: "Enable Low Power Mode (System Settings > Battery > Low Power Mode > Always or Only on Battery)"},
		{ID: "248-settings-show-time-machine-menubar", Category: "settings", Difficulty: "T1", Prompt: "Show the Time Machine icon in the menu bar"},
		{ID: "249-settings-show-battery-percent", Category: "settings", Difficulty: "T1", Prompt: "Show the battery percentage next to the menu bar battery icon"},
		{ID: "250-settings-add-dock-app", Category: "settings", Difficulty: "T2", Prompt: "Add the app 'TextEdit' to the Dock (drag from Applications, or right-click the running TextEdit and 'Keep in Dock')"},
		{ID: "251-settings-remove-dock-app", Category: "settings", Difficulty: "T2", Prompt: "Remove the app 'TextEdit' from the Dock (drag out and 'Remove' or right-click > Options > Remove from Dock)"},
		{ID: "252-settings-dock-position", Category: "settings", Difficulty: "T2", Prompt: "Move the Dock to the Left side of the screen (System Settings > Desktop & Dock > Position on screen: Left)"},
		{ID: "253-settings-dock-size", Category: "settings", Difficulty: "T2", Prompt: "Resize the Dock to the smallest size (System Settings > Desktop & Dock > Size slider all the way left)"},
		{ID: "254-settings-mission-control-spaces", Category: "settings", Difficulty: "T2", Prompt: "Create a new Space in Mission Control (Ctrl+Up to enter Mission Control, then click '+')"},
		{ID: "255-settings-keyboard-repeat-rate", Category: "settings", Difficulty: "T2", Prompt: "Set the keyboard Key Repeat to the fastest (rightmost) setting in System Settings > Keyboard"},
		{ID: "256-settings-keyboard-shortcut", Category: "settings", Difficulty: "T2", Prompt: "Add a custom keyboard shortcut Cmd+Shift+K for the menu item 'About Safari' in Safari (System Settings > Keyboard > Keyboard Shortcuts > App Shortcuts)"},
		{ID: "257-settings-input-source-add", Category: "settings", Difficulty: "T2", Prompt: "Add a new input source (any non-current source — e.g. 'Pinyin - Simplified' or 'British English') in System Settings > Keyboard > Input Sources"},
		{ID: "258-settings-input-source-remove", Category: "settings", Difficulty: "T2", Prompt: "Remove a non-default input source from System Settings > Keyboard > Input Sources"},
		{ID: "259-settings-display-resolution", Category: "settings", Difficulty: "T2", Prompt: "Change the display resolution to 'More Space' or 'Larger Text' in System Settings > Displays (any non-current option)"},
		{ID: "260-settings-display-multi-monitor", Category: "settings", Difficulty: "T2", Prompt: "Open System Settings > Displays > Arrange and view multi-monitor arrangement (or report 'single display' if only one display is connected)"},
		{ID: "261-settings-screen-time-enable", Category: "settings", Difficulty: "T2", Prompt: "Enable Screen Time downtime (System Settings > Screen Time > Downtime > Set a schedule)"},
		{ID: "262-settings-screen-time-app-limit", Category: "settings", Difficulty: "T2", Prompt: "Set an App Limit of 1 hour/day for Safari (System Settings > Screen Time > App Limits)"},
		{ID: "263-settings-trackpad-tap-to-click", Category: "settings", Difficulty: "T2", Prompt: "Toggle 'Tap to Click' on the trackpad (System Settings > Trackpad > Point & Click)"},
		{ID: "264-settings-trackpad-three-finger-drag", Category: "settings", Difficulty: "T2", Prompt: "Enable 'Three-Finger Drag' for the trackpad (System Settings > Accessibility > Pointer Control > Trackpad Options)"},
		{ID: "265-settings-mouse-secondary-click", Category: "settings", Difficulty: "T2", Prompt: "Configure the mouse secondary click to 'Click on right side' (System Settings > Mouse). If no mouse, report and skip."},
		{ID: "266-settings-add-printer", Category: "settings", Difficulty: "T2", Prompt: "Open System Settings > Printers & Scanners > Add Printer dialog (don't actually add — just open the dialog)"},
		{ID: "267-settings-default-browser", Category: "settings", Difficulty: "T2", Prompt: "Change the default web browser (System Settings > Desktop & Dock > Default web browser) to a non-current browser"},
		{ID: "268-settings-default-mail", Category: "settings", Difficulty: "T2", Prompt: "Change the default email client (Mail app > Settings > General > Default email reader) to a different option if available"},
		{ID: "269-settings-add-login-item", Category: "settings", Difficulty: "T2", Prompt: "Add an app to login items (System Settings > General > Login Items > Open at Login > '+' > pick TextEdit)"},
		{ID: "270-settings-remove-login-item", Category: "settings", Difficulty: "T2", Prompt: "Remove a non-essential app from System Settings > General > Login Items"},
		{ID: "271-settings-energy-saver", Category: "settings", Difficulty: "T2", Prompt: "Configure 'Turn display off after' to 5 minutes (System Settings > Lock Screen)"},
		{ID: "272-settings-firewall-enable", Category: "settings", Difficulty: "T2", Prompt: "Enable the macOS firewall (System Settings > Network > Firewall > toggle on)"},
		{ID: "273-settings-screen-saver-pick", Category: "settings", Difficulty: "T2", Prompt: "Pick a different screen saver in System Settings > Screen Saver (any non-current option)"},
		{ID: "274-settings-wallpaper-change", Category: "settings", Difficulty: "T2", Prompt: "Change the desktop wallpaper to a different image in System Settings > Wallpaper"},
		{ID: "275-settings-icloud-toggle-photos", Category: "settings", Difficulty: "T2", Prompt: "Toggle iCloud Photos sync (System Settings > [Apple ID] > iCloud > Photos)"},
		{ID: "276-settings-icloud-toggle-drive", Category: "settings", Difficulty: "T2", Prompt: "Toggle iCloud Drive sync (System Settings > [Apple ID] > iCloud > iCloud Drive)"},
		{ID: "277-settings-bluetooth-pair", Category: "settings", Difficulty: "T2", Prompt: "Open the Bluetooth pairing dialog (System Settings > Bluetooth, with Bluetooth on so pairable devices are listed). Don't actually pair — just open the dialog."},
		{ID: "278-settings-export-prefs", Category: "settings", Difficulty: "T3", Prompt: "Use Terminal to export macOS user defaults to a backup file at ~/Desktop/kinbench/278-defaults.plist (defaults read > file)"},
		{ID: "279-settings-restore-default-shortcuts", Category: "settings", Difficulty: "T3", Prompt: "In System Settings > Keyboard > Keyboard Shortcuts, click 'Restore Defaults' to reset all shortcuts"},
		{ID: "280-settings-bulk-disable-startup", Category: "settings", Difficulty: "T3", Prompt: "In System Settings > General > Login Items, disable every 'Allow in the Background' app except essential ones (define essential as: Apple-signed)", TimeoutSec: 240},
		{ID: "281-settings-multi-display-mirror-toggle", Category: "settings", Difficulty: "T3", Prompt: "Toggle display mirroring on a multi-monitor setup (System Settings > Displays > Mirror Displays). If single display, report 'single display' and skip."},
		{ID: "282-settings-revoke-screen-recording", Category: "settings", Difficulty: "T3", Prompt: "In System Settings > Privacy & Security > Screen Recording, disable a non-essential app's screen recording permission"},

		// ─── Terminal (15 stubs, 283-297; 5 already implemented as 024-026, 043, 044) ───
		{ID: "283-terminal-open-new-window", Category: "terminal", Difficulty: "T1", Prompt: "Open a new Terminal window (Cmd+N)"},
		{ID: "284-terminal-open-new-tab", Category: "terminal", Difficulty: "T1", Prompt: "Open a new Terminal tab (Cmd+T)"},
		{ID: "285-terminal-clear-screen", Category: "terminal", Difficulty: "T1", Prompt: "Clear the current Terminal screen (Cmd+K or 'clear' command)"},
		{ID: "286-terminal-set-tab-color", Category: "terminal", Difficulty: "T2", Prompt: "Set the active Terminal tab's color to red (Window menu > Tab > Color)"},
		{ID: "287-terminal-rename-tab", Category: "terminal", Difficulty: "T2", Prompt: "Rename the active Terminal tab to 'KinBench 287' (Window menu > Edit Tab Title)"},
		{ID: "288-terminal-split-pane", Category: "terminal", Difficulty: "T2", Prompt: "Split the Terminal window into two panes (View menu > Split Window or Cmd+D)"},
		{ID: "289-terminal-edit-profile", Category: "terminal", Difficulty: "T2", Prompt: "Change the Terminal profile to 'Pro' or any non-default profile (Terminal > Settings > Profiles)"},
		{ID: "290-terminal-pip-install", Category: "terminal", Difficulty: "T2", Prompt: "In Terminal, run 'pip3 install --user requests' and verify the install succeeded by running 'pip3 show requests'. Write the version line of pip3 show output to ~/Desktop/kinbench/290-version.txt"},
		{ID: "291-terminal-brew-list", Category: "terminal", Difficulty: "T2", Prompt: "In Terminal, run 'brew list' and write the output to ~/Desktop/kinbench/291-brew-list.txt. If brew is not installed, write 'brew not installed' to that file."},
		{ID: "292-terminal-curl-and-save", Category: "terminal", Difficulty: "T2", Prompt: "Use curl in Terminal to fetch https://example.com and save the response body to ~/Desktop/kinbench/292-page.html"},
		{ID: "293-terminal-grep-recursive", Category: "terminal", Difficulty: "T2", Prompt: "Use grep -r in Terminal to find all files in ~/Desktop/kinbench/293-corpus/ that contain the word 'kinbench'. Write matching file paths to ~/Desktop/kinbench/293-matches.txt"},
		{ID: "294-terminal-multistep-pipeline", Category: "terminal", Difficulty: "T3", Prompt: "Use a Terminal pipeline (ls + sort + head) to find the 5 largest files in ~/Documents and write their names to ~/Desktop/kinbench/294-top5.txt", TimeoutSec: 180},
		{ID: "295-terminal-script-creation", Category: "terminal", Difficulty: "T3", Prompt: "In Terminal, create a shell script at ~/Desktop/kinbench/295-script.sh that prints 'hello kinbench', make it executable, run it, capture output to ~/Desktop/kinbench/295-output.txt"},
		{ID: "296-terminal-process-management", Category: "terminal", Difficulty: "T3", Prompt: "Find the PID of a running TextEdit process via 'pgrep TextEdit', kill it with kill -TERM, verify it's gone by re-running pgrep. Write 'killed PID <N>' to ~/Desktop/kinbench/296-kill.txt"},
		{ID: "297-terminal-network-diagnose", Category: "terminal", Difficulty: "T3", Prompt: "Use ping (3 packets) and traceroute (max 5 hops) to diagnose connectivity to apple.com. Write a combined report to ~/Desktop/kinbench/297-diagnose.txt", TimeoutSec: 180},

		// ─── Pages (14 stubs, 298-311; 1 already implemented as 027) ───
		{ID: "298-pages-bold-selection", Category: "pages", Difficulty: "T1", Prompt: "In an open Pages document, select the phrase 'KinBench 298' and make it bold (Cmd+B)"},
		{ID: "299-pages-add-image", Category: "pages", Difficulty: "T1", Prompt: "Insert the image ~/Desktop/kinbench/299-photo.jpg into the open Pages document"},
		{ID: "300-pages-set-margins", Category: "pages", Difficulty: "T1", Prompt: "Change the document margins to 1 inch on all sides (Document inspector > Margins)"},
		{ID: "301-pages-create-table", Category: "pages", Difficulty: "T2", Prompt: "Insert a 3-row × 3-column table into the Pages document (Insert > Table)"},
		{ID: "302-pages-add-bulleted-list", Category: "pages", Difficulty: "T2", Prompt: "Add a bulleted list with 3 items ('Apple', 'Banana', 'Cherry') to the Pages document"},
		{ID: "303-pages-set-font", Category: "pages", Difficulty: "T2", Prompt: "Change the font of the selected paragraph to Helvetica 14pt"},
		{ID: "304-pages-set-line-spacing", Category: "pages", Difficulty: "T2", Prompt: "Set line spacing of the entire document to 1.5x"},
		{ID: "305-pages-add-page-break", Category: "pages", Difficulty: "T2", Prompt: "Insert a page break at the cursor position (Insert menu > Page Break)"},
		{ID: "306-pages-add-header-footer", Category: "pages", Difficulty: "T2", Prompt: "Add a header to the Pages document containing the text 'KinBench 306'"},
		{ID: "307-pages-spell-check", Category: "pages", Difficulty: "T2", Prompt: "Run spell check on the Pages document (Edit > Spelling and Grammar > Check Document Now)"},
		{ID: "308-pages-track-changes", Category: "pages", Difficulty: "T2", Prompt: "Enable Track Changes mode in Pages (Edit > Track Changes)"},
		{ID: "309-pages-comment", Category: "pages", Difficulty: "T2", Prompt: "Add a comment 'KinBench 309 comment' to the first paragraph of the Pages document (Insert > Comment)"},
		{ID: "310-pages-template-resume", Category: "pages", Difficulty: "T3", Prompt: "Create a new Pages document from the Resume template, replace the placeholder name with 'Jacky Sun' and email with 'sxm1981@gmail.com'. Save to ~/Desktop/kinbench/310-resume.pages", TimeoutSec: 300},
		{ID: "311-pages-merge-text-from-files", Category: "pages", Difficulty: "T3", Prompt: "Read the contents of three files in ~/Desktop/kinbench/311-sources/ (a.txt, b.txt, c.txt), concatenate them in order, and create a Pages document at ~/Desktop/kinbench/311-merged.pages containing the combined text", TimeoutSec: 300},

		// ─── Numbers (14 stubs, 312-325; 1 already implemented as 028) ───
		{ID: "312-numbers-bold-cell", Category: "numbers", Difficulty: "T1", Prompt: "In the open Numbers spreadsheet, make cell A1's value bold"},
		{ID: "313-numbers-fill-color", Category: "numbers", Difficulty: "T1", Prompt: "Set the background color of cell A1 to yellow"},
		{ID: "314-numbers-create-formula", Category: "numbers", Difficulty: "T2", Prompt: "In the open Numbers spreadsheet (with values in A1:A5), enter the formula =SUM(A1:A5) into cell A6"},
		{ID: "315-numbers-add-row", Category: "numbers", Difficulty: "T2", Prompt: "Insert a new row above row 3 in the open Numbers spreadsheet"},
		{ID: "316-numbers-add-column", Category: "numbers", Difficulty: "T2", Prompt: "Insert a new column before column B in the open Numbers spreadsheet"},
		{ID: "317-numbers-format-currency", Category: "numbers", Difficulty: "T2", Prompt: "Format the values in column A as USD currency with 2 decimal places"},
		{ID: "318-numbers-add-chart", Category: "numbers", Difficulty: "T2", Prompt: "Insert a 2D bar chart from the data in A1:B10"},
		{ID: "319-numbers-sort-data", Category: "numbers", Difficulty: "T2", Prompt: "Sort the rows in the active Numbers table by column A in ascending order"},
		{ID: "320-numbers-filter-rows", Category: "numbers", Difficulty: "T2", Prompt: "Filter the active Numbers table to show only rows where column A is greater than 100"},
		{ID: "321-numbers-merge-cells", Category: "numbers", Difficulty: "T2", Prompt: "Merge cells A1 and B1 in the active Numbers table"},
		{ID: "322-numbers-freeze-row", Category: "numbers", Difficulty: "T2", Prompt: "Freeze the first (header) row of the active Numbers table"},
		{ID: "323-numbers-import-csv", Category: "numbers", Difficulty: "T3", Prompt: "Import the CSV file ~/Desktop/kinbench/323-data.csv into a new Numbers spreadsheet, save the spreadsheet to ~/Desktop/kinbench/323-imported.numbers", TimeoutSec: 240},
		{ID: "324-numbers-pivot-aggregate", Category: "numbers", Difficulty: "T3", Prompt: "Given a Numbers table with 'Category' (column A) and 'Amount' (column B), create a summary table that totals the Amount per Category in a separate sheet", TimeoutSec: 300},
		{ID: "325-numbers-export-pdf", Category: "numbers", Difficulty: "T3", Prompt: "Export the active Numbers spreadsheet as PDF to ~/Desktop/kinbench/325-sheet.pdf (File > Export To > PDF)"},

		// ─── Keynote (10 stubs, 326-335) ───
		{ID: "326-keynote-create-blank", Category: "keynote", Difficulty: "T1", Prompt: "Create a new blank Keynote presentation (File > New) and save to ~/Desktop/kinbench/326-deck.key", TimeoutSec: 240},
		{ID: "327-keynote-add-slide", Category: "keynote", Difficulty: "T1", Prompt: "Add a new slide to the existing Keynote presentation (Slide menu > New Slide or Cmd+Shift+N)"},
		{ID: "328-keynote-add-title", Category: "keynote", Difficulty: "T2", Prompt: "Add a title slide with the text 'KinBench Keynote 328' as the title"},
		{ID: "329-keynote-change-theme", Category: "keynote", Difficulty: "T2", Prompt: "Change the Keynote presentation's theme to 'Modern Portfolio' or any non-default theme"},
		{ID: "330-keynote-add-image-to-slide", Category: "keynote", Difficulty: "T2", Prompt: "Insert the image ~/Desktop/kinbench/330-photo.jpg into the current Keynote slide"},
		{ID: "331-keynote-add-bullets", Category: "keynote", Difficulty: "T2", Prompt: "Add a content slide with 3 bullet points: 'First', 'Second', 'Third'"},
		{ID: "332-keynote-set-transition", Category: "keynote", Difficulty: "T2", Prompt: "Set the transition between slides 1 and 2 to 'Cube' (Animate inspector > Add Effect > Cube)"},
		{ID: "333-keynote-rearrange-slides", Category: "keynote", Difficulty: "T2", Prompt: "Move slide 3 to position 1 in the slide navigator"},
		{ID: "334-keynote-export-pdf", Category: "keynote", Difficulty: "T3", Prompt: "Export the open Keynote presentation as PDF to ~/Desktop/kinbench/334-deck.pdf (File > Export To > PDF)"},
		{ID: "335-keynote-build-from-outline", Category: "keynote", Difficulty: "T3", Prompt: "Read the markdown outline at ~/Desktop/kinbench/335-outline.md (each '#' heading is a slide title; bullet items become slide bullets), create a 5-slide presentation from it, save to ~/Desktop/kinbench/335-deck.key", TimeoutSec: 360},

		// ─── Music (10 stubs, 336-345) ───
		{ID: "336-music-play-pause", Category: "music", Difficulty: "T1", Prompt: "Play (or pause if currently playing) the current track in Music"},
		{ID: "337-music-skip-forward", Category: "music", Difficulty: "T1", Prompt: "Skip to the next track in Music"},
		{ID: "338-music-volume-down", Category: "music", Difficulty: "T1", Prompt: "Lower the Music app's playback volume by 10% (or by 3 menu-bar volume key presses)"},
		{ID: "339-music-create-playlist", Category: "music", Difficulty: "T2", Prompt: "Create a new playlist titled 'KinBench Mix 339'"},
		{ID: "340-music-add-to-playlist", Category: "music", Difficulty: "T2", Prompt: "Add the song currently playing (or any song from the library) to the playlist 'KinBench Mix 340'"},
		{ID: "341-music-search-library", Category: "music", Difficulty: "T2", Prompt: "Search the Music library for 'Beatles' (or any artist with multiple matches)"},
		{ID: "342-music-play-album", Category: "music", Difficulty: "T2", Prompt: "Play a specific album from the library (any album with at least one song)"},
		{ID: "343-music-shuffle-toggle", Category: "music", Difficulty: "T2", Prompt: "Toggle shuffle mode in Music (Controls > Shuffle)"},
		{ID: "344-music-export-playlist", Category: "music", Difficulty: "T3", Prompt: "Write the names of all tracks in the playlist 'KinBench Mix 344' to a text file at ~/Desktop/kinbench/344-tracks.txt (one track title per line)"},
		{ID: "345-music-stats-most-played", Category: "music", Difficulty: "T3", Prompt: "Find the most-played song in the Music library (highest play count) and write its title and artist to ~/Desktop/kinbench/345-top.txt", TimeoutSec: 240},

		// ─── Photos (10 stubs, 346-355) ───
		{ID: "346-photos-favorite", Category: "photos", Difficulty: "T1", Prompt: "Mark a specific photo (the most recent one in the library) as Favorite (heart it)"},
		{ID: "347-photos-show-info", Category: "photos", Difficulty: "T1", Prompt: "Open the Get Info panel for a specific photo (Cmd+I)"},
		{ID: "348-photos-rotate-photo", Category: "photos", Difficulty: "T1", Prompt: "Rotate a specific photo 90° clockwise (Image menu > Rotate Clockwise or Cmd+R)"},
		{ID: "349-photos-create-album", Category: "photos", Difficulty: "T2", Prompt: "Create a new album titled 'KinBench Album 349' in Photos"},
		{ID: "350-photos-add-to-album", Category: "photos", Difficulty: "T2", Prompt: "Add a specific photo to the album 'KinBench Album 350'"},
		{ID: "351-photos-edit-crop", Category: "photos", Difficulty: "T2", Prompt: "Crop a specific photo to a square aspect ratio (Edit mode > Crop > Square)", TimeoutSec: 240},
		{ID: "352-photos-edit-filter", Category: "photos", Difficulty: "T2", Prompt: "Apply the 'Vivid' filter to a specific photo (Edit mode > Filters > Vivid)"},
		{ID: "353-photos-create-memory", Category: "photos", Difficulty: "T2", Prompt: "Create a Memory from the album 'KinBench Album 353' (right-click album > Create Memory)"},
		{ID: "354-photos-search-then-tag", Category: "photos", Difficulty: "T3", Prompt: "Search Photos for photos taken in the last 30 days, mark the first 3 results as Favorite", TimeoutSec: 240},
		{ID: "355-photos-export-album", Category: "photos", Difficulty: "T3", Prompt: "Export every photo in the album 'KinBench Album 355' to ~/Desktop/kinbench/355-export/", TimeoutSec: 360},

		// ─── Maps (5 stubs, 356-360) ───
		{ID: "356-maps-search-location", Category: "maps", Difficulty: "T1", Prompt: "Open Maps and search for 'Apple Park, Cupertino'"},
		{ID: "357-maps-get-directions", Category: "maps", Difficulty: "T2", Prompt: "In Maps, get driving directions from current location to 'Apple Park, Cupertino'"},
		{ID: "358-maps-save-favorite", Category: "maps", Difficulty: "T2", Prompt: "Save 'Apple Park, Cupertino' to Favorites in Maps"},
		{ID: "359-maps-share-location", Category: "maps", Difficulty: "T2", Prompt: "In Maps, share the location 'Apple Park, Cupertino' via Mail (Share button > Mail). Save the resulting email as a draft."},
		{ID: "360-maps-multi-stop-route", Category: "maps", Difficulty: "T3", Prompt: "Plan a multi-stop route in Maps: from current location → 'Apple Park, Cupertino' → 'Stanford University' → 'Half Moon Bay'", TimeoutSec: 300},

		// ─── Multi-app (9 stubs, 361-369; 5 already implemented as 029, 030, 048-050) ───
		{ID: "361-multi-photo-from-camera-to-mail", Category: "multi-app", Difficulty: "T3", Prompt: "Open Photo Booth, take a photo, save it to ~/Desktop/kinbench/361-photo.jpg, then attach that photo to a Mail draft with subject 'KinBench 361'", TimeoutSec: 360},
		{ID: "362-multi-search-then-calendar", Category: "multi-app", Difficulty: "T3", Prompt: "Search Mail for messages with subject containing 'flight'. From the most recent match, find the departure date/time, create a calendar event titled 'KinBench Flight 362' with that start time", TimeoutSec: 360},
		{ID: "363-multi-clipboard-then-note", Category: "multi-app", Difficulty: "T3", Prompt: "Open Safari, navigate to https://en.wikipedia.org/wiki/macOS, copy the first paragraph to the clipboard, then create a note titled 'KinBench Clipboard 363' containing that paragraph", TimeoutSec: 240},
		{ID: "364-multi-screenshot-then-pages", Category: "multi-app", Difficulty: "T3", Prompt: "Take a screenshot of the current screen, save to ~/Desktop/kinbench/364-shot.png, create a new Pages document with the screenshot inserted, save the doc to ~/Desktop/kinbench/364-doc.pages", TimeoutSec: 360},
		{ID: "365-multi-music-pause-then-screenshot", Category: "multi-app", Difficulty: "T3", Prompt: "Pause Music playback (Cmd+Space in Music or menu bar) and then take a screenshot of the current desktop, save to ~/Desktop/kinbench/365-shot.png", TimeoutSec: 240},
		{ID: "366-multi-finder-then-quicklook", Category: "multi-app", Difficulty: "T3", Prompt: "Find a PDF file in ~/Documents (use Finder), open it in Preview, then take a screenshot of the Preview window and save to ~/Desktop/kinbench/366-shot.png", TimeoutSec: 300},
		{ID: "367-multi-spotlight-then-mail", Category: "multi-app", Difficulty: "T3", Prompt: "Use Spotlight to find a contact named 'Apple' (the company), copy their email address, compose a Mail draft to that address with subject 'KinBench 367'. If no Apple contact, use any contact with an email and report the contact's name.", TimeoutSec: 300},
		{ID: "368-multi-reminders-then-calendar", Category: "multi-app", Difficulty: "T3", Prompt: "List all reminders due today in the Reminders app, create matching calendar events tomorrow at the same time of day", TimeoutSec: 360},
		{ID: "369-multi-notes-export-then-mail", Category: "multi-app", Difficulty: "T3", Prompt: "Export the Note titled 'KinBench Export 369' as PDF, save to ~/Desktop/kinbench/369-note.pdf, attach to a Mail draft with subject 'KinBench 369'", TimeoutSec: 360},
	}
}
